[workspace]
resolver = "2"
members = ["anda_core", "anda_engine", "anda_lancedb", "agents/*", "tools/*"]

[workspace.package]
description = "Anda is a framework for AI agent development, designed to build a highly composable, autonomous, and perpetually memorizing network of AI agents."
repository = "https://github.com/ldclabs/anda"
homepage = "https://github.com/ldclabs/anda"
keywords = ["ai-agent", "icp", "tee"]
categories = [
  "accessibility",
  "web-programming",
  "development-tools",
  "text-processing",
]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.8", features = [
  "http1",
  "http2",
  "json",
  # "macros",
  "matched-path",
  "tokio",
  "query",
], default-features = true }
axum-core = "0.5"
axum-server = { version = "0.7", features = ["tls-rustls"] }
bytes = "1"
candid = "0.10"
ciborium = "0.2"
futures = "0.3"
futures-util = "0.3"
http = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_bytes = "0.11"
ic_cose_types = "0.6"
ic_cose = "0.6"
ic_object_store = "0.6"
ic-agent = "0.39"
ic_tee_agent = "0.2"
ic_tee_cdk = "0.2"
object_store = { version = "0.10.2" }
tokio-util = "0.7"
tokio = { version = "1", features = ["full"] }
structured-logger = "1"
rand = "0.8"
reqwest = { version = "0.12", features = [
  "rustls-tls",
  "rustls-tls-native-roots",
  "json",
  "gzip",
  "stream",
  "http2",
  # "hickory-dns",
], default-features = true }
thiserror = "2"
moka = { version = "0.12", features = ["future"] }
xid = "1.1"
toml = "0.8"
ed25519-consensus = "2.1"
log = "0.4"
chrono = "0.4"
dotenv = "0.15"
schemars = { version = "0.8" }

[profile.release]
debug = false
lto = true
strip = true
opt-level = 's'
