[workspace]
members = []
resolver = "2"

[profile.release]
debug = false
lto = true
strip = true
opt-level = 's'

[workspace.package]
name = "anda"
description = "Anda is a framework for AI agent development, designed to build a highly composable, autonomous, and perpetually memorizing network of AI agents."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ldclabs/anda"
keywords = ["ai-agent", "icp", "tee"]
categories = ["web-programming"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
axum = { version = "0.7", features = [
  "http1",
  "http2",
  "json",
  "macros",
  "matched-path",
  "tokio",
  "query",
], default-features = true }
axum-server = { version = "0.7", features = ["tls-rustls"] }
bytes = "1"
base64 = "0.22"
candid = "0.10"
ciborium = "0.2"
const-hex = "1"
lazy_static = "1.5"
serde = "1"
serde_json = "1"
serde_bytes = "0.11"
ic_cose_types = "0.6"
ic_cose = "0.6"
tokio = { version = "1", features = ["full"] }
log = "0.4"
structured-logger = "1"
reqwest = { version = "0.12", features = [
  "rustls-tls",
  "rustls-tls-native-roots",
  "json",
  "gzip",
  "stream",
  "http2",
  # "hickory-dns",
], default-features = true }
thiserror = "2"
