name: anda_bot_image
on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Docker image tag'
        required: true
        type: string
  # push:
  #   tags:
  #     - 'v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ldclabs/anda_bot
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build the Docker image
      run: |
        cd agents/anda_bot
        docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
        IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_enclave_amd64:${{ inputs.build_tag }}"
        LATEST_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_enclave_amd64:latest"
        TAGS="-t ${IMAGE_TAG} -t ${LATEST_TAG}"
        docker build -f nitro_enclave/amd64.Dockerfile $TAGS --push .
