name: Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          sudo apt-get install -y protobuf-compiler
          rustup update --no-self-update stable
          cargo clippy --all-targets --all-features
          cargo test --workspace -- --nocapture
